### ISSUE TITLE
Module 2. 10:

### ISSUE THREAD

**Issue by viettrung2103** [ilkkamtk/JavaScript-english#2]
I think this block of code: 
```
The winner is pamela with 3 votes.
results:
pamela: 3 votes
frank: 1 votes
ellie: 1 votes
```
should be like this:

```
The winner is pamela with 3 votes.
results:
pamela: 3 votes
frank: 1 vote
ellie: 1 vote
```

depending on the number of votes, it should printing out `vote` or `votes`.

**Comment by ilkkamtk** [comment]
Not required at this level. Obviously one can do it if they want.
